[colors.bright]
black = "#808080"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#87CEEB"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.primary]
background = "0x000000"
foreground = "#d4d4d4"

[font]
size = 12.0

[font.bold]
# family = "JetBrainsMono Nerd Font Mono"
family = "JetBrainsMono Nerd Font Propo"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Propo"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Propo"
style = "Regular"

[window]
decorations = "none"


